# Generated by Django 5.1.3 on 2024-11-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProducto', models.CharField(max_length=10)),
                ('DescripcionProducto', models.CharField(max_length=255)),
                ('Estatus', models.BooleanField()),
            ],
        ),
    ]
